### ISSUE TITLE
关于activity重启后收到滞后response的问题

### ISSUE THREAD

**Issue by ruintazila** [KunMinX/VIABUS-Architecture#11]
之前也做过一个类似的b/s架构
当时用类似对称加密的机制根据请求时间生成了一个唯一的密钥 只有response的密钥匹配才会更新UI  你这个应该也可以用相同的方法解决

**Comment by KunMinX** [comment]
谢谢你的建议！我复述一下对上述方案的理解：
在每个页面中各自存储一个临时的请求时间（精确到毫秒）列表，在响应时如该页面的列表中存在该时间，便更新相应的页面。
